name: flutty_state
description: "Lightweight and reactive state management solution for Flutter."
version: 0.3.0
homepage: https://github.com/Flutty-Lab/flutty_state
repository: https://github.com/Flutty-Lab/flutty_state
issue_tracker: https://github.com/Flutty-Lab/flutty_state/issues

topics:
  - state-management
  - flutter
  - widgets
  - bloc

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"


dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  flutty_ds: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
